# Node.js runtime as parent image
FROM node:20-slim

# working directory 
WORKDIR /app

# Install pnpm
RUN npm install -g pnpm

# Copy package.json and pnpm-lock.yaml
COPY package.json pnpm-lock.yaml ./

# Install dependencies
RUN pnpm install

# Copy the rest of the application code
COPY . .

# Expose Next.js port
EXPOSE 3000

# Run app
CMD ["pnpm", "run", "dev"]
