version: '3.8'

services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./server/.env
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: ./server/Containerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    depends_on:
      - db
      - redis
    restart: unless-stopped

  frontend:
    build:
      context: ./client
      dockerfile: ./Containerfile
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
