version: '3.8'

networks:
  blog-network:
    driver: bridge

services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./server/.env
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - blog-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - blog-network

  backend:
    build:
      context: .
      dockerfile: ./server/Containerfile
    command: sh -c "while ! nc -z db 5432; do sleep 1; done; python /app/create_admin.py && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    cap_add:
      - NET_RAW
    security_opt:
      - seccomp=unconfined
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env.prod
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - blog-network

  frontend:
    build:
      context: ./client
      dockerfile: ./Containerfile
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - blog-network

volumes:
  postgres_data: