# Python runtime as a parent image
FROM python:3.12-slim-bookworm

# working directory 
WORKDIR /app

COPY requirements.txt .
RUN apt-get update && apt-get install -y netcat-openbsd iputils-ping dnsutils && rm -rf /var/lib/apt/lists/*

# Install packages in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the server directory contents into the container at /app
COPY server/ /app

# Expose FastAPI port
EXPOSE 8000

# Run app
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
